<?php

function mymodule_menu(){
  $items['admin/structure/test'] = array(
  	'title' => 'My Admin Page',
    'description' => 'My description for My Admin Page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mymodule_get_form'),
    'access callback' => TRUE,
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/test/%form/confirm'] = array(
    'title' => 'Confirm',
    'description' => 'Confirm',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mymodule_get_confirm',4, 5),
    'access callback' => TRUE,
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}
function form_load(){
  
}
function mymodule_abc_view(){
	return 'test';
}

function mymodule_get_form($form, &$form_state){
  $result = db_select('user_warn', 'uw')
            ->fields('uw', array('wid','user_name', 'user_email'))
            ->execute()
            ->fetchAssoc();

  $form['user_name'] = array(
    '#type' => 'textfield',
    '#description' => t('The user name.'),
    '#title' => t('Warning User Name'),
    '#size' => '40',
    '#maxlength' => 120,
    '#required' => TRUE,
    '#default_value' => $result['user_name'],
    '#attributes' => array('class' => array('test')),
  );

  $form['user_email'] = array(
    '#type' => 'textfield',
    '#description' => t('The subject of the e-mail which will be sent to users.'),
    '#title' => t('Warn User Email'),
    '#size' => '40',
    '#maxlength' => 120,
    '#required' => TRUE,
    '#default_value' => $result['user_email'],
    '#attributes' => array('class' => array('test', 't')),
  );
  
  $form_state['test'] = $result;
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Configuration'),
  );
  return $form;
}

function mymodule_get_form_submit($form, &$form_state){
  $form_state['redirect'] = 'admin/structure/test/confirm/'.$form_state['values']['user_name'].'/'.$form_state['values']['user_email'].'/'.$form_state['test']['wid'];
  
}

function mymodule_get_confirm($form, $form_state, $name, $email, $wid){

  return confirm_form('Are you sure save the configuration?', 'admin/structure/test/', 'Your Configuration will be saved in the database', 'Yes', 'No');
}


function mymodule_get_confirm_submit($form, &$form_state){
  print_r($form_state);die;
  $result = db_select('user_warn', 'uw')
            ->fields('uw', array('wid','user_name', 'user_email'))
            ->execute()
            ->fetchAssoc();
  if(empty($result))
    $result = db_insert('user_warn')
            ->fields(array(
              'user_name' => $form_state['values']['user_name'],
              'user_email' => $form_state['values']['user_email'],
            ))
            ->execute();
  else
    $result = db_update('user_warn')
            ->fields(array(
              'user_name' => $form_state['values']['user_name'],
              'user_email' => $form_state['values']['user_email'],
            ))
            ->condition('wid', $form_state['test']['wid'], '=')
            ->execute();
}